CREATE TABLE `mlb_players` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brId` varchar(32) NOT NULL,
	`mlbamId` int,
	`name` varchar(255) NOT NULL,
	`position` varchar(64),
	`bats` varchar(4),
	`throws` varchar(4),
	`currentTeamBrAbbrev` varchar(8),
	`isActive` boolean NOT NULL DEFAULT true,
	`lastSyncedAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mlb_players_id` PRIMARY KEY(`id`),
	CONSTRAINT `mlb_players_brId_unique` UNIQUE(`brId`)
);
--> statement-breakpoint
CREATE TABLE `mlb_teams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dbSlug` varchar(128) NOT NULL,
	`mlbId` int NOT NULL,
	`mlbCode` varchar(8) NOT NULL,
	`abbrev` varchar(8) NOT NULL,
	`vsinSlug` varchar(128) NOT NULL,
	`anSlug` varchar(128) NOT NULL,
	`anLogoSlug` varchar(32) NOT NULL,
	`brAbbrev` varchar(8) NOT NULL,
	`name` varchar(255) NOT NULL,
	`nickname` varchar(128) NOT NULL,
	`city` varchar(128) NOT NULL,
	`league` enum('AL','NL') NOT NULL,
	`division` enum('East','Central','West') NOT NULL,
	`logoUrl` text NOT NULL,
	`primaryColor` varchar(16),
	`secondaryColor` varchar(16),
	`tertiaryColor` varchar(16),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mlb_teams_id` PRIMARY KEY(`id`),
	CONSTRAINT `mlb_teams_dbSlug_unique` UNIQUE(`dbSlug`),
	CONSTRAINT `mlb_teams_mlbId_unique` UNIQUE(`mlbId`),
	CONSTRAINT `mlb_teams_mlbCode_unique` UNIQUE(`mlbCode`),
	CONSTRAINT `mlb_teams_abbrev_unique` UNIQUE(`abbrev`),
	CONSTRAINT `mlb_teams_vsinSlug_unique` UNIQUE(`vsinSlug`),
	CONSTRAINT `mlb_teams_anSlug_unique` UNIQUE(`anSlug`),
	CONSTRAINT `mlb_teams_brAbbrev_unique` UNIQUE(`brAbbrev`)
);
