CREATE TABLE `mlb_strikeout_props` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gameId` int NOT NULL,
	`side` varchar(8) NOT NULL,
	`pitcherName` varchar(128) NOT NULL,
	`pitcherHand` varchar(4),
	`retrosheetId` varchar(32),
	`mlbamId` int,
	`kProj` varchar(16),
	`kLine` varchar(16),
	`kPer9` varchar(16),
	`kMedian` varchar(16),
	`kP5` varchar(16),
	`kP95` varchar(16),
	`bookLine` varchar(16),
	`bookOverOdds` varchar(16),
	`bookUnderOdds` varchar(16),
	`pOver` varchar(16),
	`pUnder` varchar(16),
	`modelOverOdds` varchar(16),
	`modelUnderOdds` varchar(16),
	`edgeOver` varchar(16),
	`edgeUnder` varchar(16),
	`verdict` varchar(32),
	`bestEdge` varchar(16),
	`bestSide` varchar(16),
	`bestMlStr` varchar(16),
	`signalBreakdown` text,
	`matchupRows` text,
	`distribution` text,
	`inningBreakdown` text,
	`modelRunAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mlb_strikeout_props_id` PRIMARY KEY(`id`)
);
